### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jwbeech** [mohsen1/swagger.d.ts#5]
Hi There

Thank you so much for this! It is going to save me so much time not having to do this myself. 
Can I suggest 1 thing: It might be quite useful to integrate your .d.ts into the typings dependency management system as its the go to for things like this. https://github.com/typings/typings

**Comment by mohsen1** [comment]
Problem with adding this TSD repository was it's name. It has to match the npm repo name and there is no repo for this definition 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/5426

**Comment by mohsen1** [comment]
You're welcome to finish the job in that PR. I really don't have time
